import { Category, Product, DeliveryZone, BusinessSettings } from './types';

export const initialCategories: Category[] = [
  {
    id: 'cat-tvs',
    name: 'TV & Entertainment',
    slug: 'tv-entertainment',
    description: 'Smart TVs, 4K UHD, QLED, Android TVs, wall brackets, TV guards and streaming accessories',
    icon: 'Tv',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Smart TVs', '4K UHD TVs', 'QLED TVs', 'Android TVs', 'TV Wall Mounts', 'TV Guards & Protectors', 'TV Boxes & Remotes']
  },
  {
    id: 'cat-audio',
    name: 'Audio & Home Theatres',
    slug: 'audio-home-theatres',
    description: 'Home theatres, soundbars, heavy bass woofers, Bluetooth party speakers, amplifiers and mics',
    icon: 'Speaker',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Home Theatres', 'Soundbars', 'Woofer Systems', 'Bluetooth Speakers', 'Party Speakers', 'Amplifiers & Microphones']
  },
  {
    id: 'cat-refrigeration',
    name: 'Refrigeration & Freezers',
    slug: 'refrigeration-freezers',
    description: 'Single door, double door, side-by-side refrigerators, mini fridges and deep chest freezers',
    icon: 'Refrigerator',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Double Door Fridges', 'Single Door Fridges', 'Side-by-Side Fridges', 'Mini Fridges', 'Chest Freezers', 'Upright Freezers']
  },
  {
    id: 'cat-kitchen',
    name: 'Kitchen Appliances',
    slug: 'kitchen-appliances',
    description: 'Microwaves, electric kettles, high-power blenders, air fryers, rice cookers and cookers',
    icon: 'Utensils',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Microwaves', 'Blenders & Juicers', 'Air Fryers', 'Electric Kettles', 'Cookers & Hotplates', 'Toasters & Sandwich Makers']
  },
  {
    id: 'cat-home-appliances',
    name: 'Home Appliances',
    slug: 'home-appliances',
    description: 'Automatic washing machines, water dispensers, room heaters, dry/steam irons and cooling fans',
    icon: 'Zap',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Washing Machines', 'Water Dispensers', 'Heaters & Fans', 'Steam & Dry Irons', 'Vacuum Cleaners']
  },
  {
    id: 'cat-electrical',
    name: 'Electrical Accessories',
    slug: 'electrical-accessories',
    description: 'Switches, sockets, heavy duty extension boards, MCBs, distribution boxes, conduits and cables',
    icon: 'Cpu',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Switches & Sockets', 'Extension Boards', 'Surge & Voltage Guards', 'Circuit Breakers & MCBs', 'Cables & Conduits', 'Adapters & Plugs']
  },
  {
    id: 'cat-power-solar',
    name: 'Power & Solar Energy',
    slug: 'power-solar-energy',
    description: 'Solar flood lights, inverters, deep cycle solar batteries, UPS backup systems and voltage stabilizers',
    icon: 'SunMedium',
    imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
    subcategories: ['Solar Flood Lights', 'Inverters & UPS', 'Solar Batteries', 'Voltage Stabilizers', 'Emergency Rechargeable Lights']
  },
  {
    id: 'cat-security-personal',
    name: 'Security & Smart Electronics',
    slug: 'security-personal-electronics',
    description: 'WiFi CCTV cameras, DVR/NVR surveillance, fast chargers, power banks and smart sensors',
    icon: 'ShieldCheck',
    imageUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80',
    subcategories: ['CCTV & Security Cameras', 'Smart Home & Sensors', 'Fast Chargers & Cables', 'Power Banks', 'Audio Accessories']
  }
];

export const initialDeliveryZones: DeliveryZone[] = [
  {
    id: 'zone-eldoret-cbd',
    name: 'Eldoret CBD & Surrounds (Zion Mall, Pioneer, West Indies, Kapsoya)',
    fee: 0,
    estimatedTime: 'Within 1 - 3 Hours (Free Express)',
    minimumOrder: 500,
    freeThreshold: 0,
    active: true
  },
  {
    id: 'zone-uasin-gishu',
    name: 'Uasin Gishu Greater (Langas, Huruma, Maili Nne, Chepkoilel, Turbo, Moiben)',
    fee: 250,
    estimatedTime: 'Same Day Delivery (2 - 5 Hours)',
    minimumOrder: 500,
    freeThreshold: 15000,
    active: true
  },
  {
    id: 'zone-rift-western',
    name: 'Rift Valley & Western Kenya (Kitale, Kapsabet, Kakamega, Bungoma, Nakuru, Kisumu)',
    fee: 450,
    estimatedTime: 'Next Day Courier Delivery / North Rift Express',
    minimumOrder: 1000,
    freeThreshold: 30000,
    active: true
  },
  {
    id: 'zone-nairobi-central',
    name: 'Nairobi, Central & Eastern Kenya (Speedaf / Fargo / Parcel Courier)',
    fee: 550,
    estimatedTime: '24 - 48 Hours Delivery',
    minimumOrder: 1000,
    freeThreshold: 45000,
    active: true
  },
  {
    id: 'zone-coast-nationwide',
    name: 'Coast & Countrywide Rest of Kenya (Mombasa, Garissa, Lodwar, Kisii)',
    fee: 700,
    estimatedTime: '2 - 3 Days Nationwide Parcel Delivery',
    minimumOrder: 1500,
    freeThreshold: 60000,
    active: true
  },
  {
    id: 'zone-pickup-zion',
    name: 'Store Pickup (Along Zion Mall, Eldoret)',
    fee: 0,
    estimatedTime: 'Ready in 30 Minutes',
    minimumOrder: 0,
    freeThreshold: 0,
    active: true
  }
];

export const initialBusinessSettings: BusinessSettings = {
  businessName: 'MEGA CITY ELECTRONICS',
  phone: '0741775878',
  whatsapp: '0741775878',
  location: 'Along Zion Mall, Kenya',
  businessHours: 'Mon - Sat: 8:00 AM - 8:00 PM | Sun: 10:00 AM - 6:00 PM',
  announcementText: '🔥 CASH ON DELIVERY AVAILABLE COUNTRYWIDE | 📞 CALL 0741775878 | 📍 LOCATED ALONG ZION MALL',
  freeDeliveryThreshold: 20000,
  acceptOrders: true
};

export const initialProducts: Product[] = [
  // ===================== TVs & ENTERTAINMENT (20+ Items) =====================
  {
    id: 'prod-tv-01',
    name: 'Vitron 32" Frameless HD Smart Android TV (Built-in WiFi, Netflix, YouTube)',
    slug: 'vitron-32-inch-frameless-hd-smart-android-tv',
    sku: 'MC-TV-VIT32S',
    brand: 'Vitron',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'Smart TVs',
    description: 'The Vitron 32 inch frameless Smart Android TV offers crystal clear HD visual display, Dolby Audio clarity, pre-installed YouTube, Netflix, Prime Video, and full HDMI/USB multimedia playback. Features an ultra-slim bezel modern frame.',
    price: 12999,
    compareAtPrice: 15500,
    discountPercent: 16,
    stockQuantity: 18,
    lowStockThreshold: 4,
    warranty: '12 Months Official Manufacturer Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '32 Inches',
      'Display Resolution': 'HD Ready (1366 x 768)',
      'Operating System': 'Android TV OS',
      'Connectivity': '2x HDMI, 2x USB, AV In, Ethernet LAN, WiFi',
      'Audio': 'Dolby Digital Sound Output 2x 8W',
      'Power Consumption': '55W Eco-friendly'
    },
    rating: 4.8,
    reviewCount: 34,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-02',
    name: 'Vitron 43" Frameless 4K UHD Smart Google TV with Voice Remote',
    slug: 'vitron-43-inch-frameless-4k-uhd-smart-google-tv',
    sku: 'MC-TV-VIT43G',
    brand: 'Vitron',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Experience ultra vivid 4K resolution on the Vitron 43" Google TV. Comes with Google Assistant Bluetooth voice control remote, Chromecast built-in, HDR10 decoding, and fast quad-core processing for seamless streaming.',
    price: 23499,
    compareAtPrice: 28000,
    discountPercent: 16,
    stockQuantity: 14,
    lowStockThreshold: 3,
    warranty: '12 Months Official Manufacturer Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '43 Inches',
      'Display Resolution': '4K Ultra HD (3840 x 2160)',
      'Operating System': 'Google TV with Play Store',
      'HDR': 'HDR10 / HLG',
      'Audio': 'Dolby Audio 20W Stereo Speakers',
      'Ports': '3x HDMI 2.0, 2x USB, Optical Out, Bluetooth 5.0'
    },
    rating: 4.9,
    reviewCount: 48,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-03',
    name: 'Hisense 43" 4K UHD Smart VIDAA TV (Dolby Vision, DTS Virtual:X, Bezel-Less)',
    slug: 'hisense-43-inch-4k-uhd-smart-vidaa-tv',
    sku: 'MC-TV-HIS43A6K',
    brand: 'Hisense',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Hisense 43 inch 4K UHD smart TV delivers cinematic color depth with Dolby Vision HDR, sports mode, Game Mode PLUS with low input lag, and lightning-fast VIDAA U6 operating system with instant Showmax, Netflix & YouTube.',
    price: 31999,
    compareAtPrice: 37000,
    discountPercent: 14,
    stockQuantity: 10,
    lowStockThreshold: 2,
    warranty: '24 Months Official Hisense Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '43 Inches',
      'Display Resolution': '4K UHD (3840 x 2160)',
      'OS': 'VIDAA U6 OS with Voice Control',
      'HDR Support': 'Dolby Vision HDR & HDR10+',
      'Sound': 'DTS Virtual:X Sound Tuning 14W'
    },
    rating: 4.9,
    reviewCount: 56,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-04',
    name: 'TCL 43" 4K HDR Google Smart TV with Dolby Audio & Voice Command',
    slug: 'tcl-43-inch-4k-hdr-google-smart-tv',
    sku: 'MC-TV-TCL43P635',
    brand: 'TCL',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'Smart TVs',
    description: 'TCL 43" metallic bezel-less 4K TV powered by Google TV. Features AIPQ 2.0 picture processing engine, dynamic color enhancement, Dolby Audio, and hands-free Google Assistant for effortless family entertainment.',
    price: 29999,
    compareAtPrice: 34500,
    discountPercent: 13,
    stockQuantity: 12,
    lowStockThreshold: 3,
    warranty: '24 Months TCL Kenya Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '43 Inches',
      'Resolution': '3840 x 2160 4K UHD',
      'Platform': 'Google TV',
      'Processor': '64-bit Quad Core',
      'Audio': 'Dolby Audio 19W'
    },
    rating: 4.7,
    reviewCount: 22,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-05',
    name: 'TCL 50" 4K UHD Smart Google TV with Micro Dimming & Game Center',
    slug: 'tcl-50-inch-4k-uhd-smart-google-tv',
    sku: 'MC-TV-TCL50P635',
    brand: 'TCL',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Step up to a massive 50 inch screen for premier movie and sports viewing. Offers Micro Dimming technology across 1,296 zones, HDR 10, Google TV ecosystem, and high fidelity Dolby Digital audio.',
    price: 38999,
    compareAtPrice: 44000,
    discountPercent: 11,
    stockQuantity: 8,
    lowStockThreshold: 2,
    warranty: '24 Months TCL Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '50 Inches',
      'Resolution': '4K UHD (3840x2160)',
      'Smart OS': 'Google TV',
      'WiFi': 'Dual-Band 2.4G / 5G WiFi'
    },
    rating: 4.8,
    reviewCount: 19,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-06',
    name: 'TCL 55" QLED 4K Smart Google TV with 120Hz DLG & Onkyo Sound',
    slug: 'tcl-55-inch-qled-4k-smart-google-tv',
    sku: 'MC-TV-TCL55C645',
    brand: 'TCL',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'QLED TVs',
    description: 'Quantum Dot technology displaying over a billion shades of color with 93% DCI-P3 gamut. Features 120Hz DLG gaming accelerator, Dolby Vision-Atmos, and custom Onkyo premium stereo speakers.',
    price: 52999,
    compareAtPrice: 62000,
    discountPercent: 15,
    stockQuantity: 6,
    lowStockThreshold: 2,
    warranty: '24 Months TCL Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '55 Inches',
      'Panel Type': 'QLED Quantum Dot',
      'Resolution': '4K Ultra HD',
      'Refresh Rate': '120Hz Game Accelerator',
      'Audio': 'Dolby Atmos + Onkyo 20W System'
    },
    rating: 5.0,
    reviewCount: 29,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-07',
    name: 'Xiaomi 43" A Pro 4K UHD Smart Google TV with Metallic Finish',
    slug: 'xiaomi-43-inch-a-pro-4k-uhd-smart-google-tv',
    sku: 'MC-TV-XIA43A',
    brand: 'Xiaomi',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Xiaomi A Pro series offers a premium unibody metal frame, 4K UHD vivid display with MEMC motion smoothing, Dolby Audio + DTS-X dual decoding, and complete Google TV smart interface with 2GB RAM + 16GB ROM storage.',
    price: 33499,
    compareAtPrice: 38000,
    discountPercent: 12,
    stockQuantity: 9,
    lowStockThreshold: 3,
    warranty: '12 Months Official Xiaomi Warranty',
    featured: false,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '43 Inches',
      'Resolution': '4K UHD (3840 x 2160)',
      'RAM / Storage': '2GB RAM / 16GB eMMC',
      'Audio': '2x 12W Speakers (DTS Virtual:X)',
      'Cast': 'Google Cast & Miracast'
    },
    rating: 4.8,
    reviewCount: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-08',
    name: 'Xiaomi 55" QLED 4K Google Smart TV with MEMC & PatchWall',
    slug: 'xiaomi-55-inch-qled-4k-google-smart-tv',
    sku: 'MC-TV-XIA55Q',
    brand: 'Xiaomi',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'QLED TVs',
    description: 'Breathtaking color volume with Xiaomi Quantum Dot panel. Delivers true 10-bit color, Dolby Vision HDR, borderless sleek aluminum profile, and 360-degree Bluetooth voice remote.',
    price: 54999,
    compareAtPrice: 65000,
    discountPercent: 15,
    stockQuantity: 5,
    lowStockThreshold: 2,
    warranty: '12 Months Xiaomi Kenya Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '55 Inches',
      'Panel': 'Quantum Dot QLED 4K',
      'HDR': 'Dolby Vision, HDR10+, HLG',
      'Sound': '2x 15W High Output Speakers'
    },
    rating: 4.9,
    reviewCount: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-09',
    name: 'Samsung 32" T5300 Full HD Smart TV with PurColor & Clean View',
    slug: 'samsung-32-inch-t5300-full-hd-smart-tv',
    sku: 'MC-TV-SAM32T5300',
    brand: 'Samsung',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'Smart TVs',
    description: 'Samsung T5300 brings sharp Full HD 1080p resolution to a 32 inch form factor. Features Ultra Clean View, PurColor realistic shading, Tizen Smart Hub, and AirPlay 2 support.',
    price: 23999,
    compareAtPrice: 27500,
    discountPercent: 13,
    stockQuantity: 11,
    lowStockThreshold: 3,
    warranty: '24 Months Samsung Kenya Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '32 Inches',
      'Resolution': 'Full HD (1920 x 1080)',
      'Engine': 'Hyper Real Picture Engine',
      'OS': 'Samsung Tizen OS',
      'Smart Features': 'Web Browser, SmartThings App Support'
    },
    rating: 4.9,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-10',
    name: 'Samsung 43" Crystal UHD 4K Smart TV with Dynamic Crystal Color',
    slug: 'samsung-43-inch-crystal-uhd-4k-smart-tv',
    sku: 'MC-TV-SAM43CU7000',
    brand: 'Samsung',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Experience lifelike color with Crystal Processor 4K. Features Object Tracking Sound Lite (OTS Lite), Q-Symphony soundbar sync, SolarCell remote, and smart home hub integration.',
    price: 43999,
    compareAtPrice: 49500,
    discountPercent: 11,
    stockQuantity: 7,
    lowStockThreshold: 2,
    warranty: '24 Months Samsung Kenya Warranty',
    featured: true,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '43 Inches',
      'Resolution': '4K UHD (3840 x 2160)',
      'Processor': 'Crystal Processor 4K',
      'OS': 'Tizen Smart Hub'
    },
    rating: 5.0,
    reviewCount: 31,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-11',
    name: 'LG 43" 4K UHD Smart AI ThinQ TV with Magic Remote & webOS',
    slug: 'lg-43-inch-4k-uhd-smart-ai-thinq-tv',
    sku: 'MC-TV-LG43UR7300',
    brand: 'LG',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'LG UR7300 powered by alpha 5 Gen 6 AI Processor 4K. Enhances non-4K content to clear 4K, features AI Sound (Virtual 5.1 Up-mix), Game Dashboard & Optimizer, and Apple AirPlay.',
    price: 42999,
    compareAtPrice: 48000,
    discountPercent: 10,
    stockQuantity: 8,
    lowStockThreshold: 2,
    warranty: '24 Months LG Kenya Official Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '43 Inches',
      'Panel': 'Real 4K IPS Panel',
      'Processor': 'a5 Gen6 AI Processor 4K',
      'OS': 'LG webOS 23 with ThinQ AI',
      'Voice Assistant': 'LG Voice Search / Alexa Built-In'
    },
    rating: 4.9,
    reviewCount: 38,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-12',
    name: 'LG 55" 4K UHD Smart ThinQ AI TV with Filmmaker Mode',
    slug: 'lg-55-inch-4k-uhd-smart-thinq-ai-tv',
    sku: 'MC-TV-LG55UR8000',
    brand: 'LG',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Big screen masterpiece. Enjoy theater-grade cinema at home with Filmmaker Mode, HDR10 Pro, AI Brightness Control that auto-tunes to ambient room lighting, and eARC audio output.',
    price: 64999,
    compareAtPrice: 75000,
    discountPercent: 13,
    stockQuantity: 6,
    lowStockThreshold: 2,
    warranty: '24 Months LG Kenya Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '55 Inches',
      'Resolution': '4K Ultra HD (3840 x 2160)',
      'Audio Engine': 'AI Sound Pro 20W',
      'HDMI Ports': '3x HDMI with eARC support'
    },
    rating: 5.0,
    reviewCount: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-13',
    name: 'Hisense 65" 4K UHD Smart VIDAA TV with Precision Color & Dolby Atmos',
    slug: 'hisense-65-inch-4k-uhd-smart-vidaa-tv',
    sku: 'MC-TV-HIS65A6K',
    brand: 'Hisense',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: '4K UHD TVs',
    description: 'Command your living room with a giant 65-inch 4K screen. Direct Full Array LED backlight produces uniform blacks and bright highlights. DTS Virtual:X and Dolby Atmos audio immersion.',
    price: 74999,
    compareAtPrice: 88000,
    discountPercent: 15,
    stockQuantity: 4,
    lowStockThreshold: 1,
    warranty: '24 Months Hisense Kenya Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Screen Size': '65 Inches (Giant Display)',
      'Backlight': 'Direct Full Array LED',
      'OS': 'VIDAA U6 OS',
      'Sound': 'Dolby Atmos & DTS Virtual:X 24W'
    },
    rating: 4.9,
    reviewCount: 16,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-acc-01',
    name: 'Heavy Duty Universal Tilting TV Wall Mount Bracket (14" - 55")',
    slug: 'heavy-duty-universal-tilting-tv-wall-mount-bracket-14-55',
    sku: 'MC-ACC-BRKT55',
    brand: 'MegaPro',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'TV Wall Mounts',
    description: 'Solid cold-rolled steel construction rated for up to 50KG load capacity. Includes bubble level spirit guide, full mounting screw pack, and 15-degree vertical tilt adjustment.',
    price: 1499,
    compareAtPrice: 2200,
    discountPercent: 32,
    stockQuantity: 50,
    lowStockThreshold: 10,
    warranty: '5 Years Structural Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Compatible Sizes': '14 to 55 Inches',
      'VESA Compliance': '75x75 up to 400x400mm',
      'Max Weight': '50 KG',
      'Tilt Range': '-15 to +15 Degrees'
    },
    rating: 4.8,
    reviewCount: 77,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-acc-02',
    name: 'Sollatek Automatic TV Guard 5A Surge & Voltage Fluctuation Protector',
    slug: 'sollatek-automatic-tv-guard-5a-surge-voltage-protector',
    sku: 'MC-ACC-SOL-TVG',
    brand: 'Sollatek',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'TV Guards & Protectors',
    description: 'Authentic Sollatek TV Guard protects sensitive TVs, decoders, soundbars and gaming consoles against brownouts, high voltage spikes, power back surges and lightning surges with 30-second start delay.',
    price: 1850,
    compareAtPrice: 2400,
    discountPercent: 23,
    stockQuantity: 45,
    lowStockThreshold: 8,
    warranty: '5 Years Manufacturer Sollatek Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Current Rating': '5 Amps (1100W)',
      'Over-voltage Disconnect': '260V',
      'Under-voltage Disconnect': '190V',
      'Wait Time': '30 Seconds Auto Delay'
    },
    rating: 5.0,
    reviewCount: 110,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-tv-acc-03',
    name: 'Gold-Plated High Speed 4K 60Hz Braided HDMI Cable 3 Metres',
    slug: 'gold-plated-high-speed-4k-braided-hdmi-cable-3m',
    sku: 'MC-ACC-HDMI3M',
    brand: 'MegaPro',
    categoryId: 'cat-tvs',
    categoryName: 'TV & Entertainment',
    subcategory: 'TV Boxes & Remotes',
    description: 'Nylon braided 18Gbps high speed HDMI 2.0 cable with zinc alloy gold-plated connectors for uncompressed 4K video, HDR, ARC audio return, and zero interference signal transfer.',
    price: 650,
    compareAtPrice: 950,
    discountPercent: 32,
    stockQuantity: 60,
    lowStockThreshold: 15,
    warranty: '12 Months Replacement Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Cable Length': '3 Metres',
      'Standard': 'HDMI 2.0 (18Gbps)',
      'Resolution Support': '4K @ 60Hz / 1080p 144Hz',
      'Connector': '24K Gold Plated'
    },
    rating: 4.8,
    reviewCount: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== AUDIO & HOME THEATRES (15+ Items) =====================
  {
    id: 'prod-aud-01',
    name: 'Vitron V527 2.1CH Super Bass Bluetooth Multimedia Speaker System',
    slug: 'vitron-v527-21ch-super-bass-bluetooth-speaker',
    sku: 'MC-AUD-VIT527',
    brand: 'Vitron',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Woofer Systems',
    description: 'The legendary Vitron 2.1 channel sound system with deep booming subwoofer bass, dual satellite tweeters, Bluetooth 5.0 pairing, FM radio tuner, USB flash drive slot, SD card and remote control.',
    price: 4499,
    compareAtPrice: 5800,
    discountPercent: 22,
    stockQuantity: 25,
    lowStockThreshold: 5,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Output Power': '75W RMS (9,000W PMPO)',
      'Subwoofer Size': '6.5 Inch Deep Throw Bass Driver',
      'Connectivity': 'Bluetooth 5.0, USB, SD, FM, AUX In',
      'Display': 'LED Digital Display with Bass/Treble Knobs'
    },
    rating: 4.9,
    reviewCount: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-02',
    name: 'Vitron V635 3.1CH High Power Home Theatre System (10,000W PMPO)',
    slug: 'vitron-v635-31ch-high-power-home-theatre-system',
    sku: 'MC-AUD-VIT635',
    brand: 'Vitron',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Home Theatres',
    description: 'Massive 3.1 channel surround acoustics featuring three tall satellite speakers and a dedicated wooden ported subwoofer for room-shaking cinematic explosions and crystal vocal clarity.',
    price: 7999,
    compareAtPrice: 9800,
    discountPercent: 18,
    stockQuantity: 15,
    lowStockThreshold: 3,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power Output': '120W RMS (10,000W PMPO)',
      'Channels': '3.1 Surround Sound',
      'Subwoofer': '8 Inch Heavy Bass Woofer',
      'Inputs': 'Optical In, Bluetooth, USB, FM Radio, Aux'
    },
    rating: 4.8,
    reviewCount: 52,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-03',
    name: 'Tagwood T-600 3.1CH Heavy Bass Bluetooth Home Theatre',
    slug: 'tagwood-t600-31ch-heavy-bass-bluetooth-home-theatre',
    sku: 'MC-AUD-TAG600',
    brand: 'Tagwood',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Home Theatres',
    description: 'Tagwood delivers rich acoustic balance with engineered wood sound resonance, dynamic RGB equalizer lights, karaoke mic input, and heavy sub frequencies ideal for Kenyan music lovers.',
    price: 8499,
    compareAtPrice: 10500,
    discountPercent: 19,
    stockQuantity: 12,
    lowStockThreshold: 3,
    warranty: '12 Months Tagwood Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power': '135W RMS',
      'Channels': '3.1 Audio',
      'Microphone Support': 'Dual Wired Mic Jack for Karaoke',
      'Features': 'Master Bass / Echo Controls'
    },
    rating: 4.7,
    reviewCount: 39,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-04',
    name: 'Amtec 2.1CH Powerful Woofer Speaker System with FM & USB',
    slug: 'amtec-21ch-powerful-woofer-speaker-system',
    sku: 'MC-AUD-AMT21',
    brand: 'Amtec',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Woofer Systems',
    description: 'Reliable, compact yet powerful sound solution for bedsitters, living rooms and shops. Clean bass punch with intuitive remote control and full phone Bluetooth connectivity.',
    price: 3850,
    compareAtPrice: 4800,
    discountPercent: 20,
    stockQuantity: 20,
    lowStockThreshold: 4,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power': '50W RMS',
      'Subwoofer': '5.25 Inch Bass Driver',
      'Modes': 'Bluetooth / Aux / USB / SD / FM'
    },
    rating: 4.8,
    reviewCount: 64,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-05',
    name: 'Hisense 2.1CH 240W Soundbar with Wireless Subwoofer & Dolby Audio',
    slug: 'hisense-21ch-240w-soundbar-wireless-subwoofer',
    sku: 'MC-AUD-HIS-HS218',
    brand: 'Hisense',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Soundbars',
    description: 'Hisense HS218 soundbar features 4 integrated speakers and a wireless 6.5" subwoofer for deep rumble without messy cables. One-remote TV sync via HDMI ARC.',
    price: 18999,
    compareAtPrice: 23500,
    discountPercent: 19,
    stockQuantity: 8,
    lowStockThreshold: 2,
    warranty: '24 Months Hisense Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Total Power': '240 Watts',
      'Subwoofer': 'Wireless 6.5" Subwoofer',
      'Audio Formats': 'Dolby Digital & DTS Virtual:X',
      'Connections': 'HDMI ARC, Optical, Coaxial, AUX, BT 4.2'
    },
    rating: 4.9,
    reviewCount: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-06',
    name: 'Vision Plus 160W Premium Bluetooth Soundbar with Subwoofer (HDMI ARC)',
    slug: 'vision-plus-160w-premium-bluetooth-soundbar-subwoofer',
    sku: 'MC-AUD-VP-SB160',
    brand: 'Vision Plus',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Soundbars',
    description: 'Transform your TV audio into a full room theatre. Features DSP sound modes (Movie, Music, News), slim profile wall-mountable design, and dedicated bass driver.',
    price: 13499,
    compareAtPrice: 16500,
    discountPercent: 18,
    stockQuantity: 10,
    lowStockThreshold: 2,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power Output': '160W Peak Power',
      'DSP Sound Modes': '3 Preset Audio Equalizers',
      'Ports': 'HDMI ARC, Optical, USB, Bluetooth 5.0'
    },
    rating: 4.7,
    reviewCount: 27,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-07',
    name: 'LG 1000W 5.1CH DVD Home Theatre System with Tallboy Speakers',
    slug: 'lg-1000w-51ch-home-theatre-system-tallboy-speakers',
    sku: 'MC-AUD-LG-LHD657',
    brand: 'LG',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Home Theatres',
    description: 'Full 1000W RMS surround power with 4 floor-standing Tallboy speakers, center dialogue speaker, and thunderous subwoofer. Features Bass Blast engine and Bluetooth phone playback.',
    price: 36999,
    compareAtPrice: 43000,
    discountPercent: 14,
    stockQuantity: 4,
    lowStockThreshold: 1,
    warranty: '24 Months LG Kenya Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power Output': '1000W Total RMS',
      'Speakers': '4x Tallboy + Center + Subwoofer',
      'Features': 'Bass Blast, 1080p DVD Upscaling, Karaoke Mic'
    },
    rating: 5.0,
    reviewCount: 41,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-aud-08',
    name: 'Dual Wireless UHF Rechargeable Microphones for Karaoke & Events',
    slug: 'dual-wireless-uhf-rechargeable-microphones-system',
    sku: 'MC-AUD-MIC-UHF2',
    brand: 'MegaSound',
    categoryId: 'cat-audio',
    categoryName: 'Audio & Home Theatres',
    subcategory: 'Amplifiers & Microphones',
    description: 'Professional dual handheld UHF wireless microphones with 50-metre range, zero latency transmission, anti-feedback metal mesh head, and rechargeable lithium receiver.',
    price: 3200,
    compareAtPrice: 4500,
    discountPercent: 29,
    stockQuantity: 22,
    lowStockThreshold: 5,
    warranty: '6 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1520523839898-50712825e3a7?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Frequency': 'UHF 500-980MHz',
      'Range': 'Up to 50 Metres',
      'Battery': 'Rechargeable 18650 Receiver / AA Handhelds',
      'Compatibility': 'Home Theatres, Amplifiers, Mixers, PA Systems'
    },
    rating: 4.8,
    reviewCount: 35,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== REFRIGERATION & FREEZERS (10+ Items) =====================
  {
    id: 'prod-ref-01',
    name: 'Vitron 166 Litres Double Door Defrost Refrigerator with Lock & Key',
    slug: 'vitron-166l-double-door-defrost-refrigerator',
    sku: 'MC-REF-VIT166',
    brand: 'Vitron',
    categoryId: 'cat-refrigeration',
    categoryName: 'Refrigeration & Freezers',
    subcategory: 'Double Door Fridges',
    description: 'Efficient double door refrigerator featuring top freezer compartment, toughened glass shelves, vegetable crisper with humidity control, LED interior light, and low noise energy-saving compressor.',
    price: 27999,
    compareAtPrice: 33000,
    discountPercent: 15,
    stockQuantity: 8,
    lowStockThreshold: 2,
    warranty: '10 Years Compressor / 1 Year General Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '166 Litres Net',
      'Configuration': 'Double Door (Top Freezer, Bottom Fridge)',
      'Cooling Type': 'Direct Cool / Defrost',
      'Refrigerant': 'R600a Eco-Friendly Gas',
      'Energy Rating': '4 Star Low Power Consumption'
    },
    rating: 4.8,
    reviewCount: 44,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ref-02',
    name: 'Vitron 248 Litres Double Door Frost-Free Refrigerator with Multi-Air Flow',
    slug: 'vitron-248l-double-door-frost-free-refrigerator',
    sku: 'MC-REF-VIT248',
    brand: 'Vitron',
    categoryId: 'cat-refrigeration',
    categoryName: 'Refrigeration & Freezers',
    subcategory: 'Double Door Fridges',
    description: 'Spacious 248L family refrigerator with total frost-free technology (no ice buildup), multi-directional air cooling vents for even temperature, door storage for large 2L bottles, and silver metallic finish.',
    price: 37999,
    compareAtPrice: 45000,
    discountPercent: 16,
    stockQuantity: 6,
    lowStockThreshold: 2,
    warranty: '10 Years Compressor Warranty',
    featured: true,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '248 Litres Total',
      'Defrosting': 'Total No Frost Technology',
      'Shelves': 'Adjustable Tempered Glass',
      'Voltage Protection': 'Wide 160V-260V Voltage Tolerance'
    },
    rating: 4.9,
    reviewCount: 29,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ref-03',
    name: 'K-Elec 181 Litres Double Door Refrigerator with Inverter Technology',
    slug: 'k-elec-181l-double-door-refrigerator-inverter',
    sku: 'MC-REF-KEL181',
    brand: 'K-Elec',
    categoryId: 'cat-refrigeration',
    categoryName: 'Refrigeration & Freezers',
    subcategory: 'Double Door Fridges',
    description: 'K-Elec high performance refrigerator with smart inverter compressor that adjusts cooling speed dynamically to save on Kenya Power electricity bills. Includes ice tray and egg rack.',
    price: 29499,
    compareAtPrice: 35000,
    discountPercent: 16,
    stockQuantity: 7,
    lowStockThreshold: 2,
    warranty: '5 Years Compressor Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '181 Litres',
      'Inverter': 'Smart Energy Inverter Compressor',
      'Color': 'Titanium Silver Finish'
    },
    rating: 4.7,
    reviewCount: 23,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ref-04',
    name: 'Ramtons 90 Litres Single Door Compact Table Top Mini Fridge',
    slug: 'ramtons-90l-single-door-table-top-mini-fridge',
    sku: 'MC-REF-RAM90',
    brand: 'Ramtons',
    categoryId: 'cat-refrigeration',
    categoryName: 'Refrigeration & Freezers',
    subcategory: 'Mini Fridges',
    description: 'Compact 90L mini fridge perfect for bedrooms, guest rooms, hotel rooms, university hostels and small offices. Features internal chiller compartment and reversible door.',
    price: 18499,
    compareAtPrice: 22000,
    discountPercent: 16,
    stockQuantity: 14,
    lowStockThreshold: 3,
    warranty: '12 Months Ramtons Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '90 Litres',
      'Type': 'Single Door Tabletop Mini Fridge',
      'Internal Chiller': 'Included with Ice Tray',
      'Dimensions': '480 x 450 x 850 mm'
    },
    rating: 4.8,
    reviewCount: 51,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ref-05',
    name: 'Hisense 200 Litres Deep Chest Freezer with Fast Freeze & Removable Basket',
    slug: 'hisense-200l-deep-chest-freezer-fast-freeze',
    sku: 'MC-REF-HIS-FC260',
    brand: 'Hisense',
    categoryId: 'cat-refrigeration',
    categoryName: 'Refrigeration & Freezers',
    subcategory: 'Chest Freezers',
    description: 'High capacity 200L deep freezer for storing meat, butchery products, dairy and frozen goods. Up to 135 hours cool retention during power outages. Aluminum inner liner for rapid freezing.',
    price: 36499,
    compareAtPrice: 42000,
    discountPercent: 13,
    stockQuantity: 5,
    lowStockThreshold: 2,
    warranty: '24 Months Official Hisense Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '200 Litres Net',
      'Fast Freeze Function': 'Yes (-30C Super Freeze)',
      'Power Outage Holdover': 'Up to 135 Hours',
      'Defrost Drain': 'Front Drain Hole with Plug'
    },
    rating: 4.9,
    reviewCount: 32,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ref-06',
    name: 'Sollatek Automatic Fridge Guard 6A Voltage & Power Surge Protector',
    slug: 'sollatek-automatic-fridge-guard-6a-surge-protector',
    sku: 'MC-ACC-SOL-FG',
    brand: 'Sollatek',
    categoryId: 'cat-refrigeration',
    categoryName: 'Refrigeration & Freezers',
    subcategory: 'Surge & Voltage Guards',
    description: 'Essential protection for any refrigerator or deep freezer in Kenya. Disconnects instantly during dangerous voltage drops and high surges, with built-in 3-minute delay to allow compressor gas to equalize.',
    price: 1950,
    compareAtPrice: 2600,
    discountPercent: 25,
    stockQuantity: 65,
    lowStockThreshold: 10,
    warranty: '5 Years Sollatek Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Current Rating': '6 Amps (1300W)',
      'Over-voltage Cutoff': '260V',
      'Under-voltage Cutoff': '185V',
      'Compressor Delay Time': '3 Minutes'
    },
    rating: 5.0,
    reviewCount: 145,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== KITCHEN APPLIANCES (15+ Items) =====================
  {
    id: 'prod-kit-01',
    name: 'Silver Crest 4500W Commercial Heavy Duty Multi-Speed Blender with Grinder Jar',
    slug: 'silver-crest-4500w-commercial-heavy-duty-blender',
    sku: 'MC-KIT-SC4500',
    brand: 'Silver Crest',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Blenders & Juicers',
    description: 'The viral high-power 4500W commercial blender that crushes ice, grains, cassava, tiger nuts, smoothies and thick soups in seconds. Features 6 hardened stainless steel blades and 2L unbreakable BPA-free jar.',
    price: 3499,
    compareAtPrice: 4800,
    discountPercent: 27,
    stockQuantity: 40,
    lowStockThreshold: 8,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Motor Power': '4500W Pure Copper High-Torque Motor',
      'Capacity': '2.0 Litres Jug + Bonus Dry Spice Grinder',
      'Blades': '6-Leaf Wave Action Japanese Steel Blades',
      'Speed Control': '15 Variable Speeds + Instant Pulse Switch'
    },
    rating: 4.9,
    reviewCount: 130,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kit-02',
    name: 'Ramtons 20L Digital Microwave Oven with Grill Function (800W)',
    slug: 'ramtons-20l-digital-microwave-oven-grill',
    sku: 'MC-KIT-RAM-MW20',
    brand: 'Ramtons',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Microwaves',
    description: 'Ramtons 20L digital microwave with 8 auto-cooking menus, dual combination grill function for crispy browned dishes, multi-stage defrosting, and child safety lock.',
    price: 11499,
    compareAtPrice: 13500,
    discountPercent: 15,
    stockQuantity: 12,
    lowStockThreshold: 3,
    warranty: '12 Months Ramtons Warranty',
    featured: true,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '20 Litres',
      'Microwave Power': '800W / Grill 1000W',
      'Control Panel': 'Digital Touchpad with LED Clock',
      'Auto Menus': 'Popcorn, Pizza, Meat, Veggies, Beverage'
    },
    rating: 4.8,
    reviewCount: 47,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kit-03',
    name: 'Sayona 6.5 Litres XXL Touchscreen Digital Air Fryer with 360 Hot Air Vortex',
    slug: 'sayona-65l-xxl-touchscreen-digital-air-fryer',
    sku: 'MC-KIT-SAY-AF65',
    brand: 'Sayona',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Air Fryers',
    description: 'Fry chicken, chips, mandazi, sausages and bake pastries with 90% less oil. Large 6.5L square basket fits whole 2KG chicken. Non-stick dishwasher safe basket and 8 preset culinary modes.',
    price: 6999,
    compareAtPrice: 9000,
    discountPercent: 22,
    stockQuantity: 18,
    lowStockThreshold: 4,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '6.5 Litres XXL Family Size',
      'Power': '1800W Rapid Air Circulation',
      'Temperature Range': '80C to 200C',
      'Timer': 'Up to 60 Minutes Auto Shut-off'
    },
    rating: 4.9,
    reviewCount: 68,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kit-04',
    name: 'Scarlett 2.0 Litres Cordless Stainless Steel Fast Boiling Electric Kettle',
    slug: 'scarlett-20l-cordless-stainless-steel-electric-kettle',
    sku: 'MC-KIT-SCA-KT20',
    brand: 'Scarlett',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Electric Kettles',
    description: 'Durable food-grade 304 stainless steel electric kettle. Fast 1500W heating element boils 2 litres of water in under 4 minutes. Features auto shut-off and dry-boil protection.',
    price: 850,
    compareAtPrice: 1200,
    discountPercent: 29,
    stockQuantity: 60,
    lowStockThreshold: 12,
    warranty: '6 Months Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1594213114663-ddfdeb30e206?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '2.0 Litres',
      'Power': '1500W High Speed Element',
      'Body Material': 'Brushed Stainless Steel',
      'Base': '360 Degree Rotational Cordless Base'
    },
    rating: 4.7,
    reviewCount: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kit-05',
    name: 'Ramtons 1.8 Litres Non-Stick Automatic Rice Cooker & Steamer',
    slug: 'ramtons-18l-non-stick-automatic-rice-cooker',
    sku: 'MC-KIT-RAM-RC18',
    brand: 'Ramtons',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Cookers & Hotplates',
    description: 'Cooks fluffy rice, pilau, biryani and steams vegetables simultaneously with top steaming basket. Auto switch to Keep-Warm mode prevents burning.',
    price: 3699,
    compareAtPrice: 4500,
    discountPercent: 18,
    stockQuantity: 16,
    lowStockThreshold: 3,
    warranty: '12 Months Ramtons Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '1.8 Litres (Up to 10 Cups of Rice)',
      'Power': '700W',
      'Accessories': 'Steamer Tray, Measuring Cup, Serving Spatula'
    },
    rating: 4.8,
    reviewCount: 37,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kit-06',
    name: 'Heavy Duty 2500W Double Spiral Cast Iron Electric Hot Plate',
    slug: 'heavy-duty-2500w-double-spiral-electric-hot-plate',
    sku: 'MC-KIT-HP-DBL',
    brand: 'MegaPro',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Cookers & Hotplates',
    description: 'Dual burner electric cooker with independent 5-level thermostat controls. High durability cast iron heating rings with anti-slip rubber feet and overheat safety thermostat.',
    price: 2450,
    compareAtPrice: 3200,
    discountPercent: 23,
    stockQuantity: 28,
    lowStockThreshold: 5,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power': '1500W + 1000W (2500W Total)',
      'Heating Elements': 'Dual Cast Iron Sealed Plates',
      'Controls': 'Twin Thermostat Dials'
    },
    rating: 4.6,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-kit-07',
    name: 'Sonifer 4-Slice Non-Stick Sandwich Maker & Panini Press',
    slug: 'sonifer-4-slice-non-stick-sandwich-maker-panini-press',
    sku: 'MC-KIT-SON-SW4',
    brand: 'Sonifer',
    categoryId: 'cat-kitchen',
    categoryName: 'Kitchen Appliances',
    subcategory: 'Toasters & Sandwich Makers',
    description: 'Non-stick easy-clean plates that toast, grill and seal 4 triangular sandwiches or thick panini rolls simultaneously with dual indicator lights.',
    price: 1999,
    compareAtPrice: 2700,
    discountPercent: 26,
    stockQuantity: 24,
    lowStockThreshold: 5,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power': '1400W Fast Toasting',
      'Plates': 'PFOA-Free Teflon Coating',
      'Safety': 'Cool-Touch Locking Handle'
    },
    rating: 4.8,
    reviewCount: 31,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== HOME APPLIANCES (10+ Items) =====================
  {
    id: 'prod-hom-01',
    name: 'Ramtons 8KG Front Load Fully Automatic Washing Machine with 15 Wash Programs',
    slug: 'ramtons-8kg-front-load-fully-automatic-washing-machine',
    sku: 'MC-HOM-RAM-WM8',
    brand: 'Ramtons',
    categoryId: 'cat-home-appliances',
    categoryName: 'Home Appliances',
    subcategory: 'Washing Machines',
    description: 'Ramtons front load washer with BLDC inverter motor for whisper-quiet performance. Features 95C hot water allergy care wash, quick 15-minute express cycle, 1200 RPM spin speed, and memory backup.',
    price: 46999,
    compareAtPrice: 54000,
    discountPercent: 13,
    stockQuantity: 5,
    lowStockThreshold: 1,
    warranty: '10 Years Motor Warranty / 2 Years Unit',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Washing Capacity': '8.0 KG (Family Size)',
      'Spin Speed': '1200 RPM Fast Drying',
      'Motor': 'Direct Inverter Brushless Motor',
      'Energy Efficiency': 'A+++ Energy & Water Saving'
    },
    rating: 4.9,
    reviewCount: 28,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-hom-02',
    name: 'Bruhm 7KG Twin Tub Semi-Automatic Washing Machine with Spin Dryer',
    slug: 'bruhm-7kg-twin-tub-semi-automatic-washing-machine',
    sku: 'MC-HOM-BRU-WM7T',
    brand: 'Bruhm',
    categoryId: 'cat-home-appliances',
    categoryName: 'Home Appliances',
    subcategory: 'Washing Machines',
    description: 'High durability twin-tub washing machine with separate wash and high-speed spin tubs. Low power and water usage, runs easily on small backup generators and solar systems.',
    price: 22999,
    compareAtPrice: 27000,
    discountPercent: 15,
    stockQuantity: 7,
    lowStockThreshold: 2,
    warranty: '12 Months Bruhm Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Wash Capacity': '7.0 KG / Spin 5.5 KG',
      'Body': 'Rust-Free Polypropylene Cabinet',
      'Filter': 'Magic Lint Filter Included'
    },
    rating: 4.7,
    reviewCount: 39,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-hom-03',
    name: 'Ramtons Hot & Normal Freestanding Water Dispenser with Bottom Cabinet',
    slug: 'ramtons-hot-normal-freestanding-water-dispenser',
    sku: 'MC-HOM-RAM-WD',
    brand: 'Ramtons',
    categoryId: 'cat-home-appliances',
    categoryName: 'Home Appliances',
    subcategory: 'Water Dispensers',
    description: 'Durable freestanding water dispenser with instant boiling water for tea/coffee and room temperature water. Includes spacious bottom storage cabinet for cups and accessories.',
    price: 8999,
    compareAtPrice: 11000,
    discountPercent: 18,
    stockQuantity: 10,
    lowStockThreshold: 2,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Taps': 'Dual Faucet (Hot & Normal)',
      'Heating Capacity': '5L/hr at >=90C',
      'Safety': 'Child Safety Lock on Hot Tap'
    },
    rating: 4.8,
    reviewCount: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-hom-04',
    name: 'Philips 2000W Non-Stick Ceramic EasySpeed Steam Iron with Calc-Clean',
    slug: 'philips-2000w-non-stick-ceramic-steam-iron',
    sku: 'MC-HOM-PHI-GC1752',
    brand: 'Philips',
    categoryId: 'cat-home-appliances',
    categoryName: 'Home Appliances',
    subcategory: 'Steam & Dry Irons',
    description: 'Smooth ceramic non-stick soleplate glides effortlessly over all fabrics. Delivers continuous 25g/min steam and 100g steam boost to conquer stubborn creases.',
    price: 3499,
    compareAtPrice: 4200,
    discountPercent: 17,
    stockQuantity: 25,
    lowStockThreshold: 5,
    warranty: '24 Months Philips Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power': '2000W Fast Heatup',
      'Steam Boost': '100g Deep Penetrating Steam',
      'Soleplate': 'Ceramic Scratch-Resistant Plate'
    },
    rating: 4.9,
    reviewCount: 58,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-hom-05',
    name: 'Heavy Duty 2000W Oscillating Quartz Room Space Heater with Anti-Tilt Switch',
    slug: 'heavy-duty-2000w-oscillating-quartz-room-heater',
    sku: 'MC-HOM-HTR2000',
    brand: 'MegaPro',
    categoryId: 'cat-home-appliances',
    categoryName: 'Home Appliances',
    subcategory: 'Heaters & Fans',
    description: 'Fast instant warming for cold Eldoret and highland nights. Features 4 quartz heating bars, wide 90-degree oscillation, safety tip-over switch, and cool touch frame.',
    price: 2350,
    compareAtPrice: 3200,
    discountPercent: 27,
    stockQuantity: 30,
    lowStockThreshold: 6,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power Levels': '400W / 800W / 1200W / 2000W',
      'Heating Elements': '4 Ruby Quartz Tubes',
      'Safety': 'Auto Shut-off Tip-over Sensor'
    },
    rating: 4.8,
    reviewCount: 49,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== ELECTRICAL ACCESSORIES (30+ Items) =====================
  {
    id: 'prod-elec-01',
    name: 'MegaPro 6-Way Heavy Duty Surge Protected Extension Board (3M Pure Copper Cord)',
    slug: 'megapro-6-way-heavy-duty-surge-extension-board-3m',
    sku: 'MC-EL-EXT6W3M',
    brand: 'MegaPro',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Extension Boards',
    description: 'Heavy duty 13A British standard 6-gang extension socket with individual neon switches, fire-retardant casing, 3-metre heavy pure copper cable, and 10,000A lightning surge protector.',
    price: 1450,
    compareAtPrice: 2000,
    discountPercent: 28,
    stockQuantity: 50,
    lowStockThreshold: 10,
    warranty: '24 Months Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Sockets': '6 Individual Switched Sockets',
      'Max Load': '13A / 3250W Max Capacity',
      'Cord Length': '3 Metres 3x1.5mm2 Pure Copper',
      'Surge Rating': '350 Joules Metal Oxide Varistor'
    },
    rating: 4.9,
    reviewCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-02',
    name: 'MegaPro 4-Way Extension Socket with Dual Fast USB-A + USB-C Ports (2M)',
    slug: 'megapro-4-way-extension-socket-dual-usb-c-2m',
    sku: 'MC-EL-EXT4USB',
    brand: 'MegaPro',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Extension Boards',
    description: 'Modern desktop power strip with 4 universal AC outlets, 20W PD Type-C port, and 2 smart USB-A charging ports. Charge phones and laptops directly without adapters.',
    price: 1650,
    compareAtPrice: 2300,
    discountPercent: 28,
    stockQuantity: 35,
    lowStockThreshold: 6,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'AC Outlets': '4x 13A Sockets',
      'USB Ports': '1x USB-C (20W PD) + 2x USB-A (18W QC3.0)',
      'Safety': 'Child Safety Shutter & Overload Reset Button'
    },
    rating: 4.8,
    reviewCount: 54,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-03',
    name: 'Schneider Electric 13A Twin Switched Socket Outlet (White Polycarbonate)',
    slug: 'schneider-electric-13a-twin-switched-socket-outlet',
    sku: 'MC-EL-SCH-TWIN',
    brand: 'Schneider',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Switches & Sockets',
    description: 'Authentic Schneider Electric Vivace series 13A 2-gang switched socket. UV resistant, fire retardant, smooth click switch mechanism for high-end residential and commercial buildings.',
    price: 450,
    compareAtPrice: 650,
    discountPercent: 30,
    stockQuantity: 120,
    lowStockThreshold: 20,
    warranty: '5 Years Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Current Rating': '13A 250V AC',
      'Gangs': 'Twin 2-Gang Switched',
      'Standards': 'BS 1363-2 Compliant'
    },
    rating: 5.0,
    reviewCount: 67,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-04',
    name: 'Schneider Electric 1-Gang 2-Way Light Switch (Vivace Series)',
    slug: 'schneider-electric-1-gang-2-way-light-switch',
    sku: 'MC-EL-SCH-SW1',
    brand: 'Schneider',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Switches & Sockets',
    description: 'Premium quality 10AX 1-gang 2-way wall light switch. Slim profile plate, long life contacts tested for over 40,000 switching operations.',
    price: 250,
    compareAtPrice: 350,
    discountPercent: 28,
    stockQuantity: 150,
    lowStockThreshold: 25,
    warranty: '5 Years Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Rating': '10AX 250V~',
      'Type': '1 Gang 2 Way Switch',
      'Material': 'High Gloss Polycarbonate'
    },
    rating: 4.9,
    reviewCount: 40,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-05',
    name: 'Chint 63A Double Pole Miniature Circuit Breaker (MCB) 6kA',
    slug: 'chint-63a-double-pole-mcb-circuit-breaker',
    sku: 'MC-EL-CHT-MCB63',
    brand: 'Chint',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Circuit Breakers & MCBs',
    description: 'Chint DZ47-63 2P 63A main isolator / circuit breaker. Provides reliable overload and short-circuit protection for domestic consumer units and distribution boards.',
    price: 850,
    compareAtPrice: 1200,
    discountPercent: 29,
    stockQuantity: 40,
    lowStockThreshold: 8,
    warranty: '24 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Rated Current': '63 Amps',
      'Poles': '2P (Double Pole)',
      'Breaking Capacity': '6kA (IEC/EN 60898-1)'
    },
    rating: 4.8,
    reviewCount: 29,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-06',
    name: 'Chint 8-Way Consumer Distribution Board (Metal Enclosure with Busbar)',
    slug: 'chint-8-way-metal-consumer-distribution-board',
    sku: 'MC-EL-CHT-DB8',
    brand: 'Chint',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Circuit Breakers & MCBs',
    description: 'Heavy gauge powder-coated metal consumer unit with transparent tinted door, neutral and earth brass terminal bars, and DIN rail mounting.',
    price: 2800,
    compareAtPrice: 3800,
    discountPercent: 26,
    stockQuantity: 20,
    lowStockThreshold: 4,
    warranty: '5 Years Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Ways': '8 DIN Modules',
      'Material': 'Flame-Retardant Metal Enclosure',
      'Protection': 'IP40 Rating'
    },
    rating: 4.9,
    reviewCount: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-07',
    name: 'MegaLux 15W High Lumens Energy-Saving LED Bulb (Pack of 5, B22 / E27)',
    slug: 'megalux-15w-energy-saving-led-bulb-pack-of-5',
    sku: 'MC-EL-BLB15W5',
    brand: 'MegaLux',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Switches & Sockets',
    description: 'Super bright 15W LED bulbs equivalent to 120W incandescent bulbs. 85% energy saving, 25,000 hours lifespan, zero flicker daylight white 6500K.',
    price: 750,
    compareAtPrice: 1100,
    discountPercent: 31,
    stockQuantity: 90,
    lowStockThreshold: 20,
    warranty: '12 Months Replacement Warranty',
    featured: false,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power': '15 Watts per bulb (1500 Lumens)',
      'Color Temperature': '6500K Cool Daylight',
      'Cap Type': 'B22 Pin / E27 Screw Options Available',
      'Lifespan': '25,000 Hours'
    },
    rating: 4.8,
    reviewCount: 92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-elec-08',
    name: 'Pure Copper Building Wire 1.5mm2 Single Core 100 Metres Roll (Red / Black)',
    slug: 'pure-copper-building-wire-15mm2-100m-roll',
    sku: 'MC-EL-CBL15',
    brand: 'EastAfricanCables',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical Accessories',
    subcategory: 'Cables & Conduits',
    description: '100% pure electrolytic copper single core PVC insulated cable. KEBS certified standard for lighting circuits in domestic and commercial installations.',
    price: 3200,
    compareAtPrice: 4200,
    discountPercent: 23,
    stockQuantity: 30,
    lowStockThreshold: 5,
    warranty: '100% KEBS Certified Pure Copper',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Conductor': '1.5mm2 Pure Stranded Copper',
      'Roll Length': '100 Metres Full Roll',
      'Voltage Rating': '450/750V',
      'Standards': 'KEBS KS 04-192 Certified'
    },
    rating: 5.0,
    reviewCount: 33,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== POWER & SOLAR ENERGY (10+ Items) =====================
  {
    id: 'prod-sol-01',
    name: 'MegaSolar 300W IP67 Waterproof Outdoor Solar LED Flood Light with Solar Panel & Remote',
    slug: 'megasolar-300w-outdoor-solar-led-flood-light',
    sku: 'MC-SOL-FLD300W',
    brand: 'MegaSolar',
    categoryId: 'cat-power-solar',
    categoryName: 'Power & Solar Energy',
    subcategory: 'Solar Flood Lights',
    description: 'Heavy duty commercial 300W solar flood light with large monocrystalline solar panel, 30,000mAh LifePO4 lithium battery, dusk-to-dawn automatic radar light sensor, and wireless remote control.',
    price: 4999,
    compareAtPrice: 6500,
    discountPercent: 23,
    stockQuantity: 28,
    lowStockThreshold: 5,
    warranty: '24 Months Replacement Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Rated Power': '300 Watts Ultra High Brightness',
      'Solar Panel': '6V 35W High Efficiency Monocrystalline',
      'Battery': '3.2V 30,000mAh LiFePO4 Lithium (Lasts 14-18 Hours)',
      'Waterproof': 'IP67 Weatherproof Die-Cast Aluminum'
    },
    rating: 4.9,
    reviewCount: 78,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sol-02',
    name: 'Must Power 1000W 12V Modified Sine Wave Solar Power Inverter with USB Output',
    slug: 'must-power-1000w-12v-solar-inverter',
    sku: 'MC-SOL-INV1000',
    brand: 'Must Power',
    categoryId: 'cat-power-solar',
    categoryName: 'Power & Solar Energy',
    subcategory: 'Inverters & UPS',
    description: 'Converts 12V DC battery power into 220V AC household electricity. Powers TVs, woofers, decoders, lighting, laptops and phone chargers seamlessly during power blackouts.',
    price: 5499,
    compareAtPrice: 7200,
    discountPercent: 23,
    stockQuantity: 14,
    lowStockThreshold: 3,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Continuous Power': '1000 Watts (2000W Peak Surge)',
      'Input Voltage': '12V DC',
      'Output Voltage': '220V - 240V AC 50Hz',
      'Protection': 'Overload, Short Circuit, Reverse Polarity Protection'
    },
    rating: 4.8,
    reviewCount: 36,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sol-03',
    name: 'Ritar 12V 100Ah Deep Cycle Solar AGM Maintenance-Free Battery',
    slug: 'ritar-12v-100ah-deep-cycle-solar-agm-battery',
    sku: 'MC-SOL-BAT100',
    brand: 'Ritar',
    categoryId: 'cat-power-solar',
    categoryName: 'Power & Solar Energy',
    subcategory: 'Solar Batteries',
    description: 'Heavy duty deep cycle AGM VRLA battery engineered for solar home systems, backup inverters and telecommunications. High discharge recovery and over 1,200 deep cycles life.',
    price: 18499,
    compareAtPrice: 22000,
    discountPercent: 15,
    stockQuantity: 8,
    lowStockThreshold: 2,
    warranty: '12 Months Manufacturer Warranty',
    featured: true,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Voltage': '12 Volts',
      'Capacity': '100Ah at 10Hr Rate',
      'Technology': 'Absorbent Glass Mat (AGM) Sealed',
      'Weight': '28.5 KG'
    },
    rating: 4.9,
    reviewCount: 24,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sol-04',
    name: 'Sollatek Automatic 1000VA Voltage Stabilizer & Regulator for Electronics',
    slug: 'sollatek-automatic-1000va-voltage-stabilizer-regulator',
    sku: 'MC-SOL-STAB1000',
    brand: 'Sollatek',
    categoryId: 'cat-power-solar',
    categoryName: 'Power & Solar Energy',
    subcategory: 'Voltage Stabilizers',
    description: 'Sollatek AVR stabilizes erratic voltages from as low as 140V or high as 280V to steady 230V safe power. Ideal for home theaters, TV setups, gaming systems and computers.',
    price: 6499,
    compareAtPrice: 8000,
    discountPercent: 18,
    stockQuantity: 12,
    lowStockThreshold: 3,
    warranty: '24 Months Sollatek Warranty',
    featured: false,
    isHotDeal: false,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '1000VA (1kVA / 800W)',
      'Input Range': '140V - 280V Wide AC',
      'Output': 'Stable 230V +/- 4%',
      'Display': 'Dual Digital Input/Output Voltage Meters'
    },
    rating: 4.9,
    reviewCount: 41,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== SECURITY & PERSONAL ELECTRONICS (10+ Items) =====================
  {
    id: 'prod-sec-01',
    name: 'V380 Pro 360 PTZ Outdoor Smart WiFi Security CCTV Camera with Color Night Vision',
    slug: 'v380-pro-360-ptz-outdoor-smart-wifi-security-camera',
    sku: 'MC-SEC-V380PTZ',
    brand: 'V380 Pro',
    categoryId: 'cat-security-personal',
    categoryName: 'Security & Smart Electronics',
    subcategory: 'CCTV & Security Cameras',
    description: 'Full 1080p HD PTZ surveillance camera with 360-degree rotation control from your Android/iPhone phone app. Features motion detection alarm, two-way audio walkie-talkie, and spotlight color night vision.',
    price: 3499,
    compareAtPrice: 4800,
    discountPercent: 27,
    stockQuantity: 25,
    lowStockThreshold: 5,
    warranty: '12 Months Warranty',
    featured: true,
    isHotDeal: true,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Resolution': '1080P Full HD (2.0 Megapixel)',
      'Pan / Tilt': 'Horizontal 355 / Vertical 90 Rotation',
      'App Support': 'V380 Pro App on Android & iOS',
      'Storage': 'MicroSD card slot up to 128GB + Cloud Support',
      'Night Vision': 'Dual Light (Infrared + 4x White Spotlights)'
    },
    rating: 4.8,
    reviewCount: 63,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sec-02',
    name: 'Oraimo 30,000mAh Ultra High Capacity Power Bank with 22.5W Fast Charging (Type-C + Dual USB)',
    slug: 'oraimo-30000mah-ultra-high-capacity-fast-charging-power-bank',
    sku: 'MC-SEC-ORA-PB30',
    brand: 'Oraimo',
    categoryId: 'cat-security-personal',
    categoryName: 'Security & Smart Electronics',
    subcategory: 'Power Banks',
    description: 'Monster 30,000mAh battery charges a smartphone 6-8 times. Supports 22.5W AniFast super charging for Samsung, iPhone, Xiaomi, Tecno & Infinix. Built-in LED flashlight and digital percentage display.',
    price: 3899,
    compareAtPrice: 4800,
    discountPercent: 18,
    stockQuantity: 30,
    lowStockThreshold: 6,
    warranty: '12 Months Official Oraimo Warranty',
    featured: true,
    isHotDeal: true,
    isNew: false,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1609592426861-1e967a57a536?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Capacity': '30,000mAh (111Wh)',
      'Fast Charge Protocols': 'PD 3.0 (20W) & QC 3.0 (22.5W)',
      'Ports': '1x Type-C Input/Output + 2x USB-A Outputs',
      'Torch': 'High Lumen Multi-Mode LED Torch'
    },
    rating: 4.9,
    reviewCount: 98,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sec-03',
    name: 'Oraimo 45W Dual Port Fast Wall Charger with 100W Type-C to Type-C Braided Cable',
    slug: 'oraimo-45w-dual-port-fast-wall-charger-type-c-cable',
    sku: 'MC-SEC-ORA-CHG45',
    brand: 'Oraimo',
    categoryId: 'cat-security-personal',
    categoryName: 'Security & Smart Electronics',
    subcategory: 'Fast Chargers & Cables',
    description: 'GaN semiconductor fast charger with USB-C and USB-A ports. Charges iPhones to 60% in 30 minutes and fast charges MacBook Air, iPads and Android flagship phones without overheating.',
    price: 1950,
    compareAtPrice: 2600,
    discountPercent: 25,
    stockQuantity: 40,
    lowStockThreshold: 8,
    warranty: '12 Months Warranty',
    featured: false,
    isHotDeal: false,
    isNew: true,
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'
    ],
    specifications: {
      'Power Output': '45W GaN Max Power',
      'Cable Included': '1.2M 100W Braided Type-C Cable',
      'Compatibility': 'iPhone 11-16, Samsung S20-S24, Laptops'
    },
    rating: 4.8,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
